# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cec68a94f66188e1a67d24a7ed260d4a3bc4d23a65aaa4670162fd6403b439b8495c236d1a1e497a0b6e28a1b07321f29275cd687affb1d387cf6fe33d0ad565

test:
  secret_key_base: 6380a3412ff62f38a87936a21d0953bccd8bc9f85b82eb56df4a305fa3d386b1fd2b08b3ffd2e7df15fb5cbeddb6c48b587612b821ad14497298327f7fa3749e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
